# -*- coding: utf-8 -*-
"""MeshroomColab_TAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AeZzxQVM5lWY11PgScsrEV5I6JgsX6cq

**Meshroom for GoogleColab - Edited by Thomas Anthony Pedersen**

2023-02-07

**0.0 - CREATE WORKING DIRECTORIES**
"""

!mkdir /content/input
!mkdir /content/meshroom
!mkdir /content/meshroomTMP

"""

> Now upload any zip files containing temp-files of previous steps computed.
Unzip in the next step

"""

from google.colab import files

!unzip 
!unzip -o '/content/outCache*.zip' -d /

"""**1. Download Meshroom 2021.1**"""

!wget -N https://github.com/alicevision/Meshroom/releases/download/v2021.1.0/Meshroom-2021.1.0-linux-cuda10.tar.gz
!tar -xvf /content/Meshroom-2021.1.0-linux-cuda10.tar.gz -C /content/meshroom

"""-

**STEP 2. ACTUAL PROCESSING**

**2.1 - PROCESS - STEP 1 - RUN CAMERAINIT_1 + FEATUREEXTRACTION_1**
"""

!/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/meshroom_batch --toNode FeatureExtraction_1 --input /content/input/ --pipeline /content/standardpipeline.mg --cache /content/meshroomTMP

!zip -r outCacheCameraInit.zip /content/meshroomTMP/CameraInit/
!zip -r outCacheFeatureExtraction.zip /content/meshroomTMP/FeatureExtraction/

files.download('outCacheCameraInit.zip')
files.download('outCacheFeatureExtraction.zip')

"""**STEP 2.2 - PROCESS - IMAGE- AND FEATUREMATCHING**"""

!/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/meshroom_batch --toNode FeatureMatching_1 --input /content/input/ --pipeline /content/standardpipeline.mg --cache /content/meshroomTMP/

!zip -r outCacheImageMatching.zip /content/meshroomTMP/ImageMatching/
!zip -r outCacheFeatureMatching.zip /content/meshroomTMP/FeatureMatching/

files.download('outCacheImageMatching.zip')
files.download('outCacheFeatureMatching.zip')

"""**STEP 2.3 - PROCESS - STRUCTURE-FROM-MOTION**"""

!/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/meshroom_batch --toNode StructureFromMotion_1 --input /content/input/ --pipeline /content/standardpipeline.mg --cache /content/meshroomTMP/

!zip -r outCacheSFM.zip /content/meshroomTMP/StructureFromMotion/

files.download('outCacheSFM.zip')

"""**STEP 2.4 - PROCESS - DEPTHMAP**"""

!/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/meshroom_batch --toNode DepthMap_1 --input /content/input/ --pipeline /content/standardpipeline.mg --cache /content/meshroomTMP/

!zip -r outCacheDepthMap.zip /content/meshroomTMP/DepthMap/

files.download('outCacheDepthMap.zip')

"""**STEP 2.5 - PROCESS - DEPTHMAP FILTER**"""

!zip -r outCacheDepthMapFilter.zip /content/meshroomTMP/DepthMapFilter/

files.download('outCacheDepthMapFilter.zip')

!/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/meshroom_batch --toNode DepthMapFilter_1 --input /content/input/ --pipeline /content/standardpipeline.mg --cache /content/meshroomTMP/

!zip -r outCacheDepthMapFilter.zip /content/meshroomTMP/DepthMapFilter/

files.download('outCacheDepthMapFilter.zip')

"""**STEP 2.6 - PROCESS - MESHING**"""

!/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/meshroom_batch --toNode Meshing_1 --input /content/input/ --pipeline /content/standardpipeline.mg --cache /content/meshroomTMP/

!zip -r outCacheMeshing.zip /content/meshroomTMP/Meshing/

files.download('outCacheMeshing.zip')

"""**STEP 2.7 - PROCESS - TEXTURING**"""

!/content/meshroom/Meshroom-2021.1.0-av2.4.0-centos7-cuda10.2/meshroom_batch --toNode Texturing_1 --input /content/input/ --pipeline /content/standardpipeline.mg --cache /content/meshroomTMP/

!zip -r outCacheTexturing.zip /content/meshroomTMP/Texturing/

files.download('outCacheTexturing.zip')